version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: Scripts/installOracleJDK8.bash
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: Scripts/serviceApp.bash
      runas: root
  ApplicationStart:
    - location: Scripts/startApp.bash
      runas: root
      ApplicationStop:
    - location: Scripts/stopApp.bash
      runas: root
  ValidateService:
    - location: Scripts/verifyApp.bash
      runas: root
