version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: scripts/installOracleJDK8.bash
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/serviceApp.bash
      runas: ubuntu
  ApplicationStart:
    - location: scripts/startApp.bash
      runas: ubuntu
      ApplicationStop:
    - location: scripts/stopApp.bash
      runas: root
  ValidateService:
    - location: scripts/verifyApp.bash
      runas: ubuntu
