version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  ApplicationStart:
    - location: scripts/startApp.bash
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stopApp.bash
      runas: root
